version: "2.1"

services:
  db:
    image: ${CONTAINER_REGISTRY?}ghloc_db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: pg_isready -U postgres
      interval: 4s
      timeout: 2s
      retries: 20

  api:
    image: ${CONTAINER_REGISTRY?}ghloc_api
    environment:
      DB_CONN: postgres://postgres:password@db:5432?sslmode=disable
      DEBUG_TOKEN: ${DEBUG_TOKEN}
    depends_on:
      db:
        condition: service_healthy
